backend:
  name: github
  repo: w-igor/mewa34
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "Aktualności"

    files:
      - file: "content/news/news.json"
        label: "Aktualności"
        name: "news"

        fields:
          - name: items
            label: Lista
            widget: list
            fields:
              - { name: body, label: Tekst, widget: text }